package com.legstar.pli2cob;


/**
 * Test the AST to COBOL converter.
 *
 */
public class ASTToCobolTest extends AbstractTester {

    /**
     * Group single item.
     * @throws CobolFormatException if conversion fails
     */
    public void testGroupItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 Group;",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 Group." + '\n'
                + "" + '\n');
    }

    /**
     * Character single item.
     * @throws CobolFormatException if conversion fails
     */
    public void testCharacterItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 Last char(20);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 Last PIC X(20)." + '\n'
                + "" + '\n');
    }

    /**
     * Character single item with varying attribute.
     * @throws CobolFormatException if conversion fails
     */
    public void testCharacterVaryingItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 Last char(20) varying;",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 Last." + '\n'
                + "           02 LEN PIC 9(4) BINARY." + '\n'
                + "           02 CHAR PIC X OCCURS 1 TO 20 DEPENDING ON LEN." + '\n'
                + "" + '\n');
    }
    /**
     * Graphic single item.
     * @throws CobolFormatException if conversion fails
     */
    public void testGraphicItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 Last graphic(20);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 Last PIC G(20) DISPLAY-1." + '\n'
                + "" + '\n');
    }

    /**
     * Widechar single item.
     * @throws CobolFormatException if conversion fails
     */
    public void testWidecharItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 Last widechar(20);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 Last PIC N(20)." + '\n'
                + "" + '\n');
    }

    /**
     * BIT strings are not supported.
     * @throws CobolFormatException if conversion fails
     */
    public void testBitItem() throws CobolFormatException {
        try {
            convertCheck(
                    "Declare 1 Last bit(20);",

                    "      *" + '\n'
                    + "      * Generated by legstar-pli2cob" + '\n'
                    + "      *" + '\n'
                    + "       01 Last PIC X(20)." + '\n'
                    + "" + '\n');
            fail();
        } catch (CobolFormatException e) {
            assertEquals("Unsupported string type: "
                    + "[level : 1,"
                    + " name : Last,"
                    + " type : BIT,"
                    + " length : 20,"
                    + " varying : NONVARYING]", e.getMessage());
        }
    }

    /**
     * Picture alphabetic single item.
     * @throws CobolFormatException if conversion fails
     */
    public void testPictureAlphabeticItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 Last pic '(5)A9XX';",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 Last PIC A(5)9XX." + '\n'
                + "" + '\n');
    }

    /**
     * Picture numeric single item.
     * @throws CobolFormatException if conversion fails
     */
    public void testPictureNumericItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 Last pic 'ZZV(3)9';",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 Last PIC ZZV9(3)." + '\n'
                + "" + '\n');
    }

    /**
     * Picture numeric with overpunch character.
     * @throws CobolFormatException if conversion fails
     */
    public void testPictureOverpunchItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 Last PIC '(5)9V(2)9T';",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 Last PIC 9(5)V9(2)9." + '\n'
                + "" + '\n');
        convertCheck(
                "Declare 1 Last PIC 'T(4)9V(3)9';",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 Last PIC 99(4)V9(3) LEADING." + '\n'
                + "" + '\n');
        convertCheck(
                "Declare 1 Last PIC '(5)9V(3)9S';",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 Last PIC S9(5)V9(3) SIGN SEPARATE." + '\n'
                + "" + '\n');
        convertCheck(
                "Declare 1 Last PIC 'S(5)9V(3)9';",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 Last PIC S9(5)V9(3) SIGN SEPARATE LEADING." + '\n'
                + "" + '\n');
    }

    /**
     * FLOAT + DECIMAL single float.
     * @throws CobolFormatException if conversion fails
     */
    public void testFloatDecimalItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 A float dec(6);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 A COMP-1." + '\n'
                + "" + '\n');
    }

    /**
     * FLOAT + DECIMAL double float.
     * @throws CobolFormatException if conversion fails
     */
    public void testDoubleDecimalItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 A float dec(16);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 A COMP-2." + '\n'
                + "" + '\n');
    }

    /**
     * FLOAT + DECIMAL single item with large precision.
     * @throws CobolFormatException if conversion fails
     */
    public void testFloatDecimalItemTooLarge() throws CobolFormatException {
        try {
            convertCheck(
                    "Declare 1 A float dec(20);",

                    "      *" + '\n'
                    + "      * Generated by legstar-pli2cob" + '\n'
                    + "      *" + '\n'
                    + "       01 Last PIC X(20)." + '\n'
                    + "" + '\n');
            fail();
        } catch (CobolFormatException e) {
            assertEquals("Unsupported precision: "
                    + "[level : 1,"
                    + " name : A,"
                    + " scale : FLOAT,"
                    + " base : DECIMAL,"
                    + " signed : true,"
                    + " precision : 20,"
                    + " scaling factor : 0]", e.getMessage());
        }
    }

    /**
     * FLOAT + BINARY single float.
     * @throws CobolFormatException if conversion fails
     */
    public void testFloatBinaryItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 A float bin(21);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 A COMP-1." + '\n'
                + "" + '\n');
    }

    /**
     * FLOAT + BINARY double float.
     * @throws CobolFormatException if conversion fails
     */
    public void testDoubleBinaryItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 A float bin(53);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 A COMP-2." + '\n'
                + "" + '\n');
    }

    /**
     * FIXED + DECIMAL .
     * @throws CobolFormatException if conversion fails
     */
    public void testFixedDecimalItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 A fixed dec(10,2);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 A PIC S9(8)V9(2) PACKED-DECIMAL." + '\n'
                + "" + '\n');
    }

    /**
     * FIXED + DECIMAL no decimal part.
     * @throws CobolFormatException if conversion fails
     */
    public void testFixedDecimalNoDecimalsItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 A fixed dec(10);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 A PIC S9(10) PACKED-DECIMAL." + '\n'
                + "" + '\n');
    }

    /**
     * FIXED + BINARY + SIGNED   PRECISION <= 7 .
     * @throws CobolFormatException if conversion fails
     */
    public void testFixedBinarySignedTinyItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 A fixed bin(7);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 A PIC X(1)." + '\n'
                + "" + '\n');
    }

    /**
     * FIXED + BINARY + SIGNED   7 < PRECISION <= 15 .
     * @throws CobolFormatException if conversion fails
     */
    public void testFixedBinarySignedShortItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 A fixed bin(15);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 A PIC S9(4) COMP-5." + '\n'
                + "" + '\n');
    }

    /**
     * FIXED + BINARY + SIGNED   15 < PRECISION <= 31 .
     * @throws CobolFormatException if conversion fails
     */
    public void testFixedBinarySignedIntegerItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 A fixed bin(31);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 A PIC S9(9) COMP-5." + '\n'
                + "" + '\n');
    }

    /**
     * FIXED + BINARY + SIGNED   31 < PRECISION <= 63 .
     * @throws CobolFormatException if conversion fails
     */
    public void testFixedBinarySignedLongItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 A fixed bin(63);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 A PIC S9(18) COMP-5." + '\n'
                + "" + '\n');
    }

    /**
     * FIXED + BINARY + UNSIGNED   PRECISION <= 8 .
     * @throws CobolFormatException if conversion fails
     */
    public void testFixedBinaryUnsignedTinyItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 A fixed bin(8) unsigned;",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 A PIC X(1)." + '\n'
                + "" + '\n');
    }

    /**
     * FIXED + BINARY + UNSIGNED   8 < PRECISION <= 16 .
     * @throws CobolFormatException if conversion fails
     */
    public void testFixedBinaryUnsignedShortItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 A fixed bin(16) unsigned;",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 A PIC 9(4) COMP-5." + '\n'
                + "" + '\n');
    }

    /**
     * FIXED + BINARY + UNSIGNED   16 < PRECISION <= 32 .
     * @throws CobolFormatException if conversion fails
     */
    public void testFixedBinaryUnsignedIntegerItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 A fixed bin(32) unsigned;",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 A PIC 9(9) COMP-5." + '\n'
                + "" + '\n');
    }

    /**
     * FIXED + BINARY + UNSIGNED   32 < PRECISION <= 64 .
     * @throws CobolFormatException if conversion fails
     */
    public void testFixedBinaryUnsignedLongItem() throws CobolFormatException {
        convertCheck(
                "Declare 1 A fixed bin(64) unsigned;",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 A PIC 9(18) COMP-5." + '\n'
                + "" + '\n');
    }

    /**
     * Test a simple array with simple dimension.
     * @throws CobolFormatException if conversion fails
     */
    public void testArraySingleDimension() throws CobolFormatException {
        convertCheck(
                "declare List fixed decimal(3) dimension(8);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 List OCCURS 8 PIC S9(3) PACKED-DECIMAL." + '\n'
                + "" + '\n');
    }

    /**
     * Test an array with a lower bound dimension.
     * @throws CobolFormatException if conversion fails
     */
    public void testArrayLowerBoundDimension() throws CobolFormatException {
        convertCheck(
                "declare List_A dimension(4:11);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 List-A OCCURS 8." + '\n'
                + "" + '\n');
    }

    /**
     * Test an array with a variable lower bound dimension.
     * @throws CobolFormatException if conversion fails
     */
    public void testArrayUnsupportedLowerBoundDimension() throws CobolFormatException {
        try {
            convertCheck(
                    "declare List_A dimension(4 refer(X):11);",

                    "      *" + '\n'
                    + "      * Generated by legstar-pli2cob" + '\n'
                    + "      *" + '\n'
                    + "       01 List-A OCCURS 8." + '\n'
                    + "" + '\n');
            fail();
        } catch (CobolFormatException e) {
            assertEquals("Unsupported variable lower bound: "
                    + "[level : 1,"
                    + " name : List_A,"
                    + " dimensions :"
                    + " [lbound :"
                    + " [bound : 4,"
                    + " refer : X],"
                    + " hbound :"
                    + " [bound : 11]]]", e.getMessage());
        }
    }

    /**
     * Test an array with a variable upper bound dimension.
     * @throws CobolFormatException if conversion fails
     */
    public void testArrayVariableUpperBoundDimension() throws CobolFormatException {
        convertCheck(
                "declare List_B dimension(1:11 refer(X));",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 List-B OCCURS 11 DEPENDING X." + '\n'
                + "" + '\n');
    }

    /**
     * Test an array with multiple dimensions.
     * @throws CobolFormatException if conversion fails
     */
    public void testArrayMultipleDimensions() throws CobolFormatException {
        convertCheck(
                "declare Table (4,2) fixed dec (3);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 Table OCCURS 8 PIC S9(3) PACKED-DECIMAL." + '\n'
                + "" + '\n');
    }

    /**
     * Single branch structure.
     * @throws CobolFormatException if conversion fails
     */
    public void testSingleBranchStructure() throws CobolFormatException {
        convertCheck(
                "Declare 1 Payroll, 4 Name, 5 Last char(20);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 Payroll." + '\n'
                + "           04 Name." + '\n'
                + "             05 Last PIC X(20)." + '\n'
                + "" + '\n');
    }

    /**
     * Multiple branch structure.
     * @throws CobolFormatException if conversion fails
     */
    public void testMultipleBranchStructure() throws CobolFormatException {
        convertCheck(
                "declare 1 Payroll, /* major structure name */"
                + " 2 Name, /* minor structure name */"
                + "     3 Last char(20), /* elementary name */"
                + "     3 First char(15),"
                + " 2 Hours,"
                + "     3 Regular fixed dec(5,2),"
                + "     3 Overtime fixed dec(5,2),"
                + " 2 Rate,"
                + "     3 Regular fixed dec(3,2),"
                + "     3 Overtime fixed dec(3,2);",

                "      *" + '\n'
                + "      * Generated by legstar-pli2cob" + '\n'
                + "      *" + '\n'
                + "       01 Payroll." + '\n'
                + "           02 Name." + '\n'
                + "             03 Last PIC X(20)." + '\n'
                + "             03 First PIC X(15)." + '\n'
                + "           02 Hours." + '\n'
                + "             03 Regular PIC S9(3)V9(2) PACKED-DECIMAL." + '\n'
                + "             03 Overtime PIC S9(3)V9(2) PACKED-DECIMAL." + '\n'
                + "           02 Rate." + '\n'
                + "             03 Regular PIC S9(1)V9(2) PACKED-DECIMAL." + '\n'
                + "             03 Overtime PIC S9(1)V9(2) PACKED-DECIMAL." + '\n'
                + "" + '\n');
    }

    /**
     * Test level formatting.
     * @throws Exception if something goes wrong
     */
    public void testFormatCobolLevel() throws Exception {
        ASTToCobol converter = new ASTToCobol();
        assertEquals("01", converter.formatLevel(1));
        assertEquals("12", converter.formatLevel(12));
        try {
            assertEquals("12", converter.formatLevel(145));
            fail();
        } catch (CobolFormatException e) {
            assertEquals("Level 145 is invalid for COBOL", e.getMessage());
        }
    }

    /**
     * Test name formatting.
     * @throws Exception if something goes wrong
     */
    public void testFormatCobolName() throws Exception {
        ASTToCobol converter = new ASTToCobol();
        assertEquals("to-5z", converter.formatName("to_5z"));
        assertEquals("a12345678901234567890123456789",
                converter.formatName("a123456789012345678901234567890"));
        assertEquals("to5z", converter.formatName("to5z"));
    }

    /**
     * A generic test helper that takes a source fragment and checks the result.
     * @param source the source fragment
     * @param expected the expected sub graph
     * @throws CobolFormatException if conversion fails
     */
    private void convertCheck(
            final String source,
            final String expected) throws CobolFormatException {
        ASTToCobol converter = new ASTToCobol();
        String cobol = converter.convert(parseAndNormalize(source));
        assertEquals(expected, cobol);
    }
}
