package com.legstar.pli2cob;

import junit.framework.TestCase;

/**
 * Test the PLIStructureToCobol class.
 *
 */
public class PLIStructureToCobolTest extends TestCase {

    /**
     * Make sure nulls don't get through.
     */
    public void testNullEntry() {
        PLIStructureToCobol pli2cob = new PLIStructureToCobol();
        try {
            pli2cob.execute(null);
            fail();
        } catch (PLIStructureLexingException e) {
            fail(e.getMessage());
        } catch (PLIStructureParsingException e) {
            fail(e.getMessage());
        } catch (CobolFormatException e) {
            fail(e.getMessage());
        } catch (PLIStructureReadingException e) {
            assertEquals("Source is null", e.getMessage());
        }
    }

    /**
     * Empty source should be supported.
     */
    public void testEmptyEntry() {
        PLIStructureToCobol pli2cob = new PLIStructureToCobol();
        try {
            assertEquals(
                    "      *" + '\n'
                    + "      * Generated by legstar-pli2cob" + '\n'
                    + "      *" + '\n'
                    , pli2cob.execute(""));
        } catch (PLIStructureLexingException e) {
            fail(e.getMessage());
        } catch (PLIStructureParsingException e) {
            fail(e.getMessage());
        } catch (CobolFormatException e) {
            fail(e.getMessage());
        } catch (PLIStructureReadingException e) {
            fail(e.getMessage());
        }
    }

    /**
     * Try garbage.
     */
    public void testGarbageEntry() {
        PLIStructureToCobol pli2cob = new PLIStructureToCobol();
        try {
            pli2cob.execute(" %ç$ ,;:");
            fail();
        } catch (PLIStructureLexingException e) {
            fail(e.getMessage());
        } catch (PLIStructureParsingException e) {
            assertEquals("Parsing token stream failed.", e.getMessage());
        } catch (CobolFormatException e) {
            fail(e.getMessage());
        } catch (PLIStructureReadingException e) {
            fail(e.getMessage());
        }
    }
    
}
